from main import app, db, UserModel

# data generated by chatGPT
dummy_users = [
    # Generation 1 (Roots)
    {'id': 1, 'first_name': 'John', 'last_name': 'Doe',
        'parent1_id': None, 'parent2_id': None},
    {'id': 2, 'first_name': 'Mary', 'last_name': 'Doe',
        'parent1_id': None, 'parent2_id': None},

    # Generation 2 (Children of John and Mary)
    {'id': 3, 'first_name': 'Alice', 'last_name': 'Doe',
        'parent1_id': 1, 'parent2_id': 2},
    {'id': 4, 'first_name': 'Bob', 'last_name': 'Doe',
        'parent1_id': 1, 'parent2_id': 2},
    {'id': 5, 'first_name': 'Charlie', 'last_name': 'Doe',
        'parent1_id': 1, 'parent2_id': 2},

    # Generation 3 (Children of Alice and Bob)
    {'id': 6, 'first_name': 'David', 'last_name': 'Doe',
        'parent1_id': 3, 'parent2_id': None},
    {'id': 7, 'first_name': 'Emily', 'last_name': 'Doe',
        'parent1_id': 3, 'parent2_id': None},
    {'id': 8, 'first_name': 'Frank', 'last_name': 'Doe',
        'parent1_id': 4, 'parent2_id': None},
    {'id': 9, 'first_name': 'Grace', 'last_name': 'Doe',
        'parent1_id': 4, 'parent2_id': None},
    {'id': 10, 'first_name': 'Hannah', 'last_name': 'Doe',
        'parent1_id': 5, 'parent2_id': None},

    # Generation 4 (Children of David, Emily, Frank, Grace, and Hannah)
    {'id': 11, 'first_name': 'Isaac', 'last_name': 'Doe',
        'parent1_id': 6, 'parent2_id': None},
    {'id': 12, 'first_name': 'Jack', 'last_name': 'Doe',
        'parent1_id': 6, 'parent2_id': None},
    {'id': 13, 'first_name': 'Lily', 'last_name': 'Doe',
        'parent1_id': 7, 'parent2_id': None},
    {'id': 14, 'first_name': 'Mia', 'last_name': 'Doe',
        'parent1_id': 7, 'parent2_id': None},
    {'id': 15, 'first_name': 'Nina', 'last_name': 'Doe',
        'parent1_id': 8, 'parent2_id': None},
    {'id': 16, 'first_name': 'Oliver', 'last_name': 'Doe',
        'parent1_id': 9, 'parent2_id': None},
    {'id': 17, 'first_name': 'Paul', 'last_name': 'Doe',
        'parent1_id': 10, 'parent2_id': None},

    # Generation 5 (Children of Isaac, Jack, Lily, Mia, Nina, Oliver, and Paul)
    {'id': 18, 'first_name': 'Quinn', 'last_name': 'Doe',
        'parent1_id': 11, 'parent2_id': None},
    {'id': 19, 'first_name': 'Ryan', 'last_name': 'Doe',
        'parent1_id': 11, 'parent2_id': None},
    {'id': 20, 'first_name': 'Sophia', 'last_name': 'Doe',
        'parent1_id': 12, 'parent2_id': None},
    {'id': 21, 'first_name': 'Tom', 'last_name': 'Doe',
        'parent1_id': 12, 'parent2_id': None},
    {'id': 22, 'first_name': 'Uma', 'last_name': 'Doe',
        'parent1_id': 13, 'parent2_id': None},
    {'id': 23, 'first_name': 'Vera', 'last_name': 'Doe',
        'parent1_id': 13, 'parent2_id': None},
    {'id': 24, 'first_name': 'Will', 'last_name': 'Doe',
        'parent1_id': 14, 'parent2_id': None},
    {'id': 25, 'first_name': 'Xena', 'last_name': 'Doe',
        'parent1_id': 14, 'parent2_id': None},
    {'id': 26, 'first_name': 'Yara', 'last_name': 'Doe',
        'parent1_id': 15, 'parent2_id': None},
    {'id': 27, 'first_name': 'Zach', 'last_name': 'Doe',
        'parent1_id': 16, 'parent2_id': None},
    {'id': 28, 'first_name': 'Alice', 'last_name': 'Doe',
        'parent1_id': 17, 'parent2_id': None},
]


def populate_db():
    with app.app_context():
        db.session.query(UserModel).delete()

        for user in dummy_users:
            new_user = UserModel(
                id=user['id'],
                first_name=user['first_name'],
                last_name=user['last_name'],
                parent1_id=user['parent1_id'],
                parent2_id=user['parent2_id']
            )
            db.session.add(new_user)

        db.session.commit()

        print("Database populated.")


populate_db()
